DELETE {{skofnung_location}}/buckets
Authorization: Basic {{skofnung_username}} {{skofnung_password}}
Content-Type: application/json

{
    "file": "date.sh",
    "folder": "upload",
    "location": "{{gungnir_location}}",
    "username": "{{gungnir_username}}",
    "password": "{{gungnir_password}}"
}

###
PUT {{skofnung_location}}/buckets
Authorization: Basic {{skofnung_username}} {{skofnung_password}}
Content-Type: application/json

{
    "script": "date",
    "file": "date.sh",
    "folder": "upload",
    "location": "{{gungnir_location}}",
    "username": "{{gungnir_username}}",
    "password": "{{gungnir_password}}"
}

###
POST {{skofnung_location}}/buckets/search
Authorization: Basic {{skofnung_username}} {{skofnung_password}}
Content-Type: application/json

{
    "file": "date.sh",
    "folder": "upload",
    "location": "{{gungnir_location}}",
    "username": "{{gungnir_username}}",
    "password": "{{gungnir_password}}"
}