# @no-cookie-jar
DELETE {{skofnung.location}}/buckets
Authorization: Basic {{skofnung.username}} {{skofnung.password}}
Content-Type: application/json

{
    "file": "date.sh",
    "folder": "upload",
    "location": "{{gungnir.location}}",
    "username": "{{gungnir.username}}",
    "password": "{{gungnir.password}}"
}

###
# @no-cookie-jar
PUT {{skofnung.location}}/buckets
Authorization: Basic {{skofnung.username}} {{skofnung.password}}
Content-Type: application/json

{
    "script": "date",
    "file": "date.sh",
    "folder": "upload",
    "location": "{{gungnir.location}}",
    "username": "{{gungnir.username}}",
    "password": "{{gungnir.password}}"
}

###
# @no-cookie-jar
POST {{skofnung.location}}/buckets/search
Authorization: Basic {{skofnung.username}} {{skofnung.password}}
Content-Type: application/json

{
    "file": "date.sh",
    "folder": "upload",
    "location": "{{gungnir.location}}",
    "username": "{{gungnir.username}}",
    "password": "{{gungnir.password}}"
}