PUT {{skofnung.location}}/deploy
Authorization: Basic {{skofnung.username}} {{skofnung.password}}
Content-Type: application/json

{
    "script": "source $1/date.sh",
    "location": "{{gungnir.location}}",
    "username": "{{gungnir.username}}",
    "password": "{{gungnir.password}}"
}