PUT {{skofnung_location}}/deploy
Authorization: Basic {{skofnung_username}} {{skofnung_password}}
Content-Type: application/json

{
    "script": "source $1/date.sh",
    "location": "{{gungnir_location}}",
    "username": "{{gungnir_username}}",
    "password": "{{gungnir_password}}"
}