POST {{skofnung_location}}/device
Authorization: Basic {{skofnung_username}} {{skofnung_password}}
Content-Type: application/json

{
    "location": "{{gungnir_location}}",
    "username": "{{gungnir_username}}",
    "password": "{{gungnir_password}}"
}

###
POST {{skofnung_location}}/health
Authorization: Basic {{skofnung_username}} {{skofnung_password}}
Content-Type: application/json

{
    "location": "{{gungnir_location}}",
    "username": "{{gungnir_username}}",
    "password": "{{gungnir_password}}"
}

###
POST {{skofnung_location}}/system
Authorization: Basic {{skofnung_username}} {{skofnung_password}}
Content-Type: application/json

{
    "location": "{{gungnir_location}}",
    "username": "{{gungnir_username}}",
    "password": "{{gungnir_password}}"
}