# @no-cookie-jar
POST {{skofnung.location}}/device
Authorization: Basic {{skofnung.username}} {{skofnung.password}}
Content-Type: application/json

{
    "location": "{{gungnir.location}}",
    "username": "{{gungnir.username}}",
    "password": "{{gungnir.password}}"
}

###
# @no-cookie-jar
POST {{skofnung.location}}/health
Authorization: Basic {{skofnung.username}} {{skofnung.password}}
Content-Type: application/json

{
    "location": "{{gungnir.location}}",
    "username": "{{gungnir.username}}",
    "password": "{{gungnir.password}}"
}

###
# @no-cookie-jar
POST {{skofnung.location}}/system
Authorization: Basic {{skofnung.username}} {{skofnung.password}}
Content-Type: application/json

{
    "location": "{{gungnir.location}}",
    "username": "{{gungnir.username}}",
    "password": "{{gungnir.password}}"
}