POST http://localhost:8080/device
Authorization: Basic admin admin
Content-Type: application/json

{
    "location": "{{location}}",
    "username": "{{username}}",
    "password": "{{password}}"
}

###
POST http://localhost:8080/health
Authorization: Basic admin admin
Content-Type: application/json

{
    "location": "{{location}}",
    "username": "{{username}}",
    "password": "{{password}}"
}

###
POST http://localhost:8080/system
Authorization: Basic admin admin
Content-Type: application/json

{
    "location": "{{location}}",
    "username": "{{username}}",
    "password": "{{password}}"
}