DELETE {{skofnung_location}}/sources/1
Authorization: Basic {{skofnung_username}} {{skofnung_password}}

###
GET {{skofnung_location}}/sources
Authorization: Basic {{skofnung_username}} {{skofnung_password}}

###
POST {{skofnung_location}}/sources
Authorization: Basic {{skofnung_username}} {{skofnung_password}}
Content-Type: application/json

{
    "script": "date",
    "file": "date.sh",
    "folder": "upload",
    "location": "{{gungnir_location}}",
    "username": "{{gungnir_username}}",
    "password": "{{gungnir_password}}"
}